config/routes.rb
Rails.application.routes.draw do
  get 'infos/me'
  get 'car_logs/new', to: 'car_logs#new'
  get 'car_logs/cars', to: 'car_logs#cars'
  root to: 'welcome#index'

  resources :car_logs

  get 'login', to: 'sessions#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_log.rb
class CarLog < ApplicationRecord
	#validates :plate_number, null:false, length: {maximum:8}

	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base 
	has_many :car_log

	validates :username,
		presence: true,
		uniqueness: { case_sensitivity: false},
		length: {minimum: 3, maximum: 5}

	validates :email 
		presence: true
		length: {maximum: 105}
		uniqueness: {case_sensitivity: false}
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_logs_controller.rb
class CarLogsController < ApplicationController
  before_action :set_car, only: [:edit, :update, :show, :delete]
  # before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :delete]
  def require_same_user
    if current_user != @car.user and !current_user.admin? 
      flash[:notice] = " "
      redirect_to root_path
    end
  end 
  def new
  	@car_logs = CarLog.new
  end

  def create
  	@car_logs = CarLog.new(car_logs_params)
    # @car_logs.user = User.last #temporary
    @car.user = current_user
  	if @car_logs.save
  		flash[:notice] = "Create New Car"


  		redirect_to car_logs_new_path(@car_logs)
  	else
  		render 'new'

  	end
  end

  def cars
  	@car_logs = CarLog.last
  end



  def destroy
    @car_logs.destroy
    flash[:notice] = 'tite'
    redirect_to car_logs(@car)
  end





  private
  def car_logs_params
  	params.require(:car_log).permit(:plate_number, :time_in, :time_out, :color, :brand)
  end

  def set_car
    @car_logs
  end 
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def aboutme
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render 'new'
	end 

	def create
		#debugger 
		#finds email 
		user = User.find_by(email: params[:session][:email].downcase)
		#user = User.find_by(email: )

		#if the user exists, itll render
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id 
			flash[:success] = "Logged in successfully"
			redirect_to user_path(user)
		else 
			flash.now[:danger] = "There was something wrong with your login"
			render 'new'
		end
	end 

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged out"
		redirect_to root_path
	end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/parking_helper.rb
module ParkingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/car_logs/cars.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		body {
			margin: 0;
			background: #222;
			font-family: sans-serif;
			font-weight: 300;
		}

		.container {
			width: 80%;
			margin: 0 auto;
		}
		header {
			background: #55d6aa;
		}

		header ::after{
			content: '';
			display: table;
			clear: both;
		}

		h1{
			margin: 0;
			font-family: sans-serif;
			font-weight:5em;
			font-size: 5em;
			padding-top: 10px;
			padding-left: 50px;
			float:left;
		}

		nav {
			float: right;
		}
		nav ul{
			margin: 0;
			padding: 0;
			list-style: none;
		}

		nav li {
			display: inline-block;
			margin-left: 60px;
			padding-top: 70px;
		}

		nav a {
			color: #444;
			text-decoration: none;
			text-transform:uppercase;
		}


	</style>	
</head>
<body>
	<header>
		<H1>Park&Go</H1>
		<div class = "container">
			<nav>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About me', infos_me_path %> </li>
				<li> <%= link_to 'New Car', car_logs_new_path %> </li>
				<li> <%= link_to 'Car Log', car_logs_cars_path %></li>
				<li> <%= link_to 'Log out', logout_path, method: :delete %></li>

			</nav>
		</div>
	</header>

<div style = "color:beige; text-align:center; font-family: sans-serif; padding-top: 30px; font-size: 2em">
	<p>
		PLATE NUMBER: <%= @car_logs.plate_number %>
	</p>
	<p>
		TIME IN: <%= @car_logs.time_in %>
	</p>
	<p>
		TIME OUT: <%= @car_logs.time_out %>
	</p>
	<p>
		COLOR: <%= @car_logs.color %>s
	</p>
	<p>
		BRAND: <%= @car_logs.brand %>
	</p>
	<p>
		CREATED AT: <%= @car_logs.created_at %>
	</p>
	<p>
		UPDATED AT: <%= @car_logs.updated_at %>
	</p>

	<% if logged_in? && current%> 

</div>
</body>
</html>

app/views/car_logs/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		body {
			margin: 0;
			background: #222;
			font-family: sans-serif;
			font-weight: 300;
		}

		.container {
			width: 80%;
			margin: 0 auto;
		}
		header {
			background: #55d6aa;
		}

		header ::after{
			content: '';
			display: table;
			clear: both;
		}

		h1{
			margin: 0;
			font-family: sans-serif;
			font-weight:5em;
			font-size: 5em;
			padding-top: 10px;
			padding-left: 50px;
			float:left;
		}

		nav {
			float: right;
		}
		nav ul{
			margin: 0;
			padding: 0;
			list-style: none;
		}

		nav li {
			display: inline-block;
			margin-left: 60px;
			padding-top: 70px;
		}

		nav a {
			color: #444;
			text-decoration: none;
			text-transform:uppercase;
		}

	</style>	
</head>
<body>
	<header>
		<H1>Park&Go</H1>
		<div class = "container">
			<nav>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About me', infos_me_path %></li>
				<li> <%= link_to 'New Car', car_logs_new_path %></li>
				<li><%= link_to 'Car Log', car_logs_cars_path %></li>
			</nav>
		</div>
	</header>

	<div style = "padding-top: 30px; padding-left: 50px; text-align: center; color: beige; font-size: 2em">

	<% if @car_logs.errors.any? %>
		<h2>Errors: </h2>
		<ul>
			<% @car_logs.errors.full_messages.each do |msg| %>
			<%= msg %>
			<% end %>
		</ul>
	 <% end %>
	 
	<%= form_for @car_logs do |s| %>
		<p>
			<%= s.label :plate_number %>
			<%= s.text_field :plate_number %>
		</p>
		<p>
			<%= s.label :user_id %>
			<%= s.text_field :user_id %>
		</p>
		<p>
			<%= s.label :time_in %>ss
			<%= s.datetime_field :time_in %>
		</p>
		<p>
			<%= s.label :time_out %>
			<%= s.datetime_field :time_out %>
		</p>
		<p>
			<%= s.label :color %>
			<%= s.select :color, ['Black', 'White', 'Red', 'Silver', 'Yellow'], :prompt => 'Select one' %>
		</p>
		<p>
			<%= s.label :brand %>
			<%= s.select :brand, ['Toyota', 'Honda', 'BMW','Mercedes','Ford','Ferrari', 'Hyundai', 'Porsche'], :prompt => 'Select one' %>
		</p>
		<p>
			Owner <%= car.user.username %>
		</p>
		<p>
			<%= s.submit %>
		</p>

		<% end %>
	</div>

</body>
</html>

app/views/infos/me.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Parking Lot</title>
	<style type="text/css">
		body {
			margin: 0;
			background: #222;
			font-family: sans-serif;
			font-weight: 300;
		}

		.container {
			width: 80%;
			margin: 0 auto;
		}
		header {
			background: #55d6aa;
		}

		header ::after{
			content: '';
			display: table;
			clear: both;
		}

		h1{
			margin: 0;
			font-family: sans-serif;
			font-weight:5em;
			font-size: 5em;
			padding-top: 10px;
			padding-left: 50px;
			float:left;
		}

		nav {
			float: right;
		}
		nav ul{
			margin: 0;
			padding: 0;
			list-style: none;
		}

		nav li {
			display: inline-block;
			margin-left: 60px;
			padding-top: 70px;
		}

		nav a {
			color: #444;
			text-decoration: none;
			text-transform:uppercase;
		}

		img {
			display: block;
    		margin-left: auto;
    		margin-right: auto;
    		padding-top: 30px;
		}

	</style>	
</head>
<body>
	<header>
		<H1>Park&Go</H1>
		<div class = "container">
			<nav>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About me', infos_me_path %> </li>
				<li> <%= link_to 'New Car', car_logs_new_path %></li>
				<li><%= link_to 'Car Log', car_logs_cars_path %></li>
			</nav>
		</div>
	</header>
	<img src= "https://scontent.fmnl10-1.fna.fbcdn.net/v/t1.0-9/42982677_2197503996957344_6434287100228534272_n.jpg?_nc_cat=103&_nc_eui2=AeFzQeprxC6nHwdKh6YX41jl7nKOtps_lNMPXdptz6h6cQzLlhVCsNtJ2LxnNYn2UhREUAKajrP-a3HEn9Mh-mXihPFcz9N_QvSu5cXZY0OZRw&_nc_ht=scontent.fmnl10-1.fna&oh=8189bd4c4e54dae6b29afaa915239d3b&oe=5C508086" width = "300" length = "300">
	<div display: inline-block>
	<p style = "font-size: 2em; font-family: sans-serif; color: beige; text-align: center"> Hello! I am Bea Basilio, 3 BS Management Information Systems from Singapore. I am passionate about cars so I wanted to start up a space where cars can conveniently park and customers are satisfied. </p>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% flash.each do |name, msg| %>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Parking Lot</title>
	<style type="text/css">
		body {
			margin: 0;
			background: #222;
			font-family: sans-serif;
			font-weight: 300;
		}

		.container {
			width: 80%;
			margin: 0 auto;
		}
		header {
			background: #55d6aa;
		}

		header ::after{
			content: '';
			display: table;
			clear: both;
		}

		h1{
			margin: 0;
			font-family: sans-serif;
			font-weight:5em;
			font-size: 5em;
			padding-top: 10px;
			padding-left: 50px;
			float:left;
		}

		nav {
			float: right;
		}
		nav ul{
			margin: 0;
			padding: 0;
			list-style: none;
		}

		nav li {
			display: inline-block;
			margin-left: 60px;
			padding-top: 70px;
		}

		nav a {
			color: #444;
			text-decoration: none;
			text-transform:uppercase;
		}

	</style>	
</head>
<body>
	<header>
		<H1>Park&Go</H1>
		<div class = "container">
			<nav>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About me', infos_me_path %> </li>
				<li> <%= link_to 'New Car', car_logs_new_path %></li>
				<li><%= link_to 'Car Log', car_logs_cars_path %></li>
			</nav>
		</div>
	</header>
	<p style = "font-size: 10em; font-family: sans-serif; text-align: center;color:beige; font-weight: 6em">Welcome!</p>
</body>
</html>